spring.datasource.url=jdbc:postgresql://monorail.proxy.rlwy.net:34466/railway
spring.datasource.username=postgres
spring.datasource.password=GhSyMWnghkoqfMjRXGeTbQGJIMyKBqvD
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false
server.port=8080

